// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaqrResturant.Data;

#nullable disable

namespace SaqrResturant.Migrations
{
    [DbContext(typeof(ResturantContext))]
    partial class ResturantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SaqrResturant.Models.ContactUsModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subject")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Inbox");
                });

            modelBuilder.Entity("SaqrResturant.Models.deliveryModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("DeliveryUserId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryUserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("SaqrResturant.Models.menuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Imgpath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("SaqrResturant.Models.OrderDetailsModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("MenuId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<double?>("itemPrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SaqrResturant.Models.orderModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<double?>("totalPrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SaqrResturant.Models.UserModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("deletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            deliveryLocation = "jenin, abu-sufyan street",
                            fullName = "mohammed jalamnih",
                            password = "1111",
                            phoneNumber = "0598516128",
                            role = 0,
                            userName = "zen2222"
                        },
                        new
                        {
                            Id = 2,
                            deliveryLocation = "jenin, nablus street",
                            fullName = "Ahmed muhaisen",
                            password = "2222",
                            phoneNumber = "059851512",
                            role = 1,
                            userName = "muhaisen"
                        },
                        new
                        {
                            Id = 3,
                            deliveryLocation = "Ramallah,jenin street",
                            fullName = "john doe",
                            password = "3333",
                            phoneNumber = "056123423",
                            role = 2,
                            userName = "doe"
                        },
                        new
                        {
                            Id = 4,
                            deliveryLocation = "nablus, jenin street",
                            fullName = "jane doe",
                            password = "4444",
                            phoneNumber = "05678923412",
                            role = 2,
                            userName = "JD"
                        },
                        new
                        {
                            Id = 5,
                            deliveryLocation = "jerusalem, salah-al-deen street",
                            fullName = "jickel mackson",
                            password = "5555",
                            phoneNumber = "05987234123",
                            role = 0,
                            userName = "MJ"
                        });
                });

            modelBuilder.Entity("SaqrResturant.Models.ContactUsModel", b =>
                {
                    b.HasOne("SaqrResturant.Models.UserModel", null)
                        .WithMany("inquiries")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("SaqrResturant.Models.deliveryModel", b =>
                {
                    b.HasOne("SaqrResturant.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("DeliveryUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SaqrResturant.Models.orderModel", "Order")
                        .WithMany("Deliveries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaqrResturant.Models.UserModel", null)
                        .WithMany("deliveries")
                        .HasForeignKey("UserModelId");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaqrResturant.Models.OrderDetailsModel", b =>
                {
                    b.HasOne("SaqrResturant.Models.menuModel", "Menu")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaqrResturant.Models.orderModel", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SaqrResturant.Models.orderModel", b =>
                {
                    b.HasOne("SaqrResturant.Models.UserModel", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaqrResturant.Models.menuModel", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SaqrResturant.Models.orderModel", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SaqrResturant.Models.UserModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("deliveries");

                    b.Navigation("inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
